[package]
name = "rust_term"
version = "0.0.1"
authors = ["Martin WernstÃ¥l <m4rw3r@gmail.com>"]

[dependencies]
clock_ticks = "*"
errno       = "*"
freetype-rs = "*"
libc        = "*"
glutin      = "*"
log         = "*"

[dependencies.glium]
version              = "*"
gl_integral_textures = true
